# Generated by Django 4.2.6 on 2024-01-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color_heart',
            field=models.BooleanField(default=False),
        ),
    ]
